# ansible nn1 -m file -a "path/home/ec2-user/nn1_dir state=directory"
---
- name: Update nn1 severs
  hosts: nn1

  tasks:
  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir
      state: directory
...
