---
- name: Install HTTP sever
  hosts: nn1
  become: yes

  tasks:
  - name: Install Apache2
    apt:
      name: apache2
      state: present

  - name: start apacha2
    service:
      name: apache2
      state: started


  - name: Enable Apache2
    service:
      name: apache2
      enabled: yes

...
