---
- name: Variables Demo
  hosts: g1
  become: yes
  vars:
    myusername: Illybanks

  tasks:
  - name: Update Dynamic page
    template:
      src: dynamicstatic.j2
      dest: /var/www/html/dynamicstat.html
...